on:
  - push
  - pull_request

jobs:
  cargo-check-features:
    name: cargo-check-features

    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - toolchain: stable
            command: cargo hack check --feature-powerset --no-dev-deps --depth 2 --skip default,nightly,cpu-mkl-matmul,cuda,cudnn
          - toolchain: nightly
            command: cargo hack check --each-feature --no-dev-deps --features nightly --skip default,cpu-mkl-matmul,cuda,cudnn

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.config.toolchain }}
          override: true
      - uses: taiki-e/install-action@cargo-hack
      - name: Check Features Combinations
        run: ${{ matrix.config.command }}
