on: [pull_request]

jobs:
  cargo-test:
    name: cargo-test-nightly

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features nightly,safetensors,numpy
      - name: test CPU f32
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features nightly,safetensors,numpy
      - name: test CPU f64
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --features nightly,test-f64,safetensors,numpy