on: [pull_request]

jobs:
  cargo-check:
    name: cargo-check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: taiki-e/install-action@cargo-hack
      - name: Check Features Combinations
        run: cargo hack check --feature-powerset --no-dev-deps --depth 2 --skip default
