on: [pull_request]

jobs:
  cargo-check:
    name: cargo-check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Check CPU
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Check CUDA
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --features test-cuda,ci-check
